name: sneaker_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.0
  path_provider: ^2.0.13
  simple_shadow: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200

    - family: Teko
      fonts:

        - asset: assets/fonts/Teko-Bold.ttf
          weight: 900
        - asset: assets/fonts/Teko-SemiBold.ttf
          weight: 900
        - asset: assets/fonts/Teko-Medium.ttf
          weight: 600
        - asset: assets/fonts/Teko-Regular.ttf
          weight: 400
        - asset: assets/fonts/Teko-Light.ttf
          weight: 300


